# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/xiaozl/bluefox2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/xiaozl/bluefox2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xiaozl/bluefox2/CMakeFiles /home/xiaozl/bluefox2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xiaozl/bluefox2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named grid

# Build rule for target.
grid: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 grid
.PHONY : grid

# fast build rule for target.
grid/fast:
	$(MAKE) -f CMakeFiles/grid.dir/build.make CMakeFiles/grid.dir/build
.PHONY : grid/fast

#=============================================================================
# Target rules for targets named bluefox2_capture

# Build rule for target.
bluefox2_capture: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bluefox2_capture
.PHONY : bluefox2_capture

# fast build rule for target.
bluefox2_capture/fast:
	$(MAKE) -f CMakeFiles/bluefox2_capture.dir/build.make CMakeFiles/bluefox2_capture.dir/build
.PHONY : bluefox2_capture/fast

#=============================================================================
# Target rules for targets named videosample

# Build rule for target.
videosample: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 videosample
.PHONY : videosample

# fast build rule for target.
videosample/fast:
	$(MAKE) -f CMakeFiles/videosample.dir/build.make CMakeFiles/videosample.dir/build
.PHONY : videosample/fast

#=============================================================================
# Target rules for targets named bluefox2_test

# Build rule for target.
bluefox2_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bluefox2_test
.PHONY : bluefox2_test

# fast build rule for target.
bluefox2_test/fast:
	$(MAKE) -f CMakeFiles/bluefox2_test.dir/build.make CMakeFiles/bluefox2_test.dir/build
.PHONY : bluefox2_test/fast

#=============================================================================
# Target rules for targets named blueflow

# Build rule for target.
blueflow: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blueflow
.PHONY : blueflow

# fast build rule for target.
blueflow/fast:
	$(MAKE) -f CMakeFiles/blueflow.dir/build.make CMakeFiles/blueflow.dir/build
.PHONY : blueflow/fast

#=============================================================================
# Target rules for targets named px4flow

# Build rule for target.
px4flow: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 px4flow
.PHONY : px4flow

# fast build rule for target.
px4flow/fast:
	$(MAKE) -f CMakeFiles/px4flow.dir/build.make CMakeFiles/px4flow.dir/build
.PHONY : px4flow/fast

#=============================================================================
# Target rules for targets named videocapture

# Build rule for target.
videocapture: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 videocapture
.PHONY : videocapture

# fast build rule for target.
videocapture/fast:
	$(MAKE) -f CMakeFiles/videocapture.dir/build.make CMakeFiles/videocapture.dir/build
.PHONY : videocapture/fast

VideoCapture.o: VideoCapture.cpp.o

.PHONY : VideoCapture.o

# target to build an object file
VideoCapture.cpp.o:
	$(MAKE) -f CMakeFiles/videocapture.dir/build.make CMakeFiles/videocapture.dir/VideoCapture.cpp.o
.PHONY : VideoCapture.cpp.o

VideoCapture.i: VideoCapture.cpp.i

.PHONY : VideoCapture.i

# target to preprocess a source file
VideoCapture.cpp.i:
	$(MAKE) -f CMakeFiles/videocapture.dir/build.make CMakeFiles/videocapture.dir/VideoCapture.cpp.i
.PHONY : VideoCapture.cpp.i

VideoCapture.s: VideoCapture.cpp.s

.PHONY : VideoCapture.s

# target to generate assembly for a file
VideoCapture.cpp.s:
	$(MAKE) -f CMakeFiles/videocapture.dir/build.make CMakeFiles/videocapture.dir/VideoCapture.cpp.s
.PHONY : VideoCapture.cpp.s

VideoSample.o: VideoSample.cpp.o

.PHONY : VideoSample.o

# target to build an object file
VideoSample.cpp.o:
	$(MAKE) -f CMakeFiles/videosample.dir/build.make CMakeFiles/videosample.dir/VideoSample.cpp.o
.PHONY : VideoSample.cpp.o

VideoSample.i: VideoSample.cpp.i

.PHONY : VideoSample.i

# target to preprocess a source file
VideoSample.cpp.i:
	$(MAKE) -f CMakeFiles/videosample.dir/build.make CMakeFiles/videosample.dir/VideoSample.cpp.i
.PHONY : VideoSample.cpp.i

VideoSample.s: VideoSample.cpp.s

.PHONY : VideoSample.s

# target to generate assembly for a file
VideoSample.cpp.s:
	$(MAKE) -f CMakeFiles/videosample.dir/build.make CMakeFiles/videosample.dir/VideoSample.cpp.s
.PHONY : VideoSample.cpp.s

blueflow.o: blueflow.cpp.o

.PHONY : blueflow.o

# target to build an object file
blueflow.cpp.o:
	$(MAKE) -f CMakeFiles/blueflow.dir/build.make CMakeFiles/blueflow.dir/blueflow.cpp.o
.PHONY : blueflow.cpp.o

blueflow.i: blueflow.cpp.i

.PHONY : blueflow.i

# target to preprocess a source file
blueflow.cpp.i:
	$(MAKE) -f CMakeFiles/blueflow.dir/build.make CMakeFiles/blueflow.dir/blueflow.cpp.i
.PHONY : blueflow.cpp.i

blueflow.s: blueflow.cpp.s

.PHONY : blueflow.s

# target to generate assembly for a file
blueflow.cpp.s:
	$(MAKE) -f CMakeFiles/blueflow.dir/build.make CMakeFiles/blueflow.dir/blueflow.cpp.s
.PHONY : blueflow.cpp.s

bluefox/bluefox2.o: bluefox/bluefox2.cpp.o

.PHONY : bluefox/bluefox2.o

# target to build an object file
bluefox/bluefox2.cpp.o:
	$(MAKE) -f CMakeFiles/grid.dir/build.make CMakeFiles/grid.dir/bluefox/bluefox2.cpp.o
	$(MAKE) -f CMakeFiles/bluefox2_capture.dir/build.make CMakeFiles/bluefox2_capture.dir/bluefox/bluefox2.cpp.o
	$(MAKE) -f CMakeFiles/videosample.dir/build.make CMakeFiles/videosample.dir/bluefox/bluefox2.cpp.o
	$(MAKE) -f CMakeFiles/bluefox2_test.dir/build.make CMakeFiles/bluefox2_test.dir/bluefox/bluefox2.cpp.o
	$(MAKE) -f CMakeFiles/blueflow.dir/build.make CMakeFiles/blueflow.dir/bluefox/bluefox2.cpp.o
	$(MAKE) -f CMakeFiles/px4flow.dir/build.make CMakeFiles/px4flow.dir/bluefox/bluefox2.cpp.o
	$(MAKE) -f CMakeFiles/videocapture.dir/build.make CMakeFiles/videocapture.dir/bluefox/bluefox2.cpp.o
.PHONY : bluefox/bluefox2.cpp.o

bluefox/bluefox2.i: bluefox/bluefox2.cpp.i

.PHONY : bluefox/bluefox2.i

# target to preprocess a source file
bluefox/bluefox2.cpp.i:
	$(MAKE) -f CMakeFiles/grid.dir/build.make CMakeFiles/grid.dir/bluefox/bluefox2.cpp.i
	$(MAKE) -f CMakeFiles/bluefox2_capture.dir/build.make CMakeFiles/bluefox2_capture.dir/bluefox/bluefox2.cpp.i
	$(MAKE) -f CMakeFiles/videosample.dir/build.make CMakeFiles/videosample.dir/bluefox/bluefox2.cpp.i
	$(MAKE) -f CMakeFiles/bluefox2_test.dir/build.make CMakeFiles/bluefox2_test.dir/bluefox/bluefox2.cpp.i
	$(MAKE) -f CMakeFiles/blueflow.dir/build.make CMakeFiles/blueflow.dir/bluefox/bluefox2.cpp.i
	$(MAKE) -f CMakeFiles/px4flow.dir/build.make CMakeFiles/px4flow.dir/bluefox/bluefox2.cpp.i
	$(MAKE) -f CMakeFiles/videocapture.dir/build.make CMakeFiles/videocapture.dir/bluefox/bluefox2.cpp.i
.PHONY : bluefox/bluefox2.cpp.i

bluefox/bluefox2.s: bluefox/bluefox2.cpp.s

.PHONY : bluefox/bluefox2.s

# target to generate assembly for a file
bluefox/bluefox2.cpp.s:
	$(MAKE) -f CMakeFiles/grid.dir/build.make CMakeFiles/grid.dir/bluefox/bluefox2.cpp.s
	$(MAKE) -f CMakeFiles/bluefox2_capture.dir/build.make CMakeFiles/bluefox2_capture.dir/bluefox/bluefox2.cpp.s
	$(MAKE) -f CMakeFiles/videosample.dir/build.make CMakeFiles/videosample.dir/bluefox/bluefox2.cpp.s
	$(MAKE) -f CMakeFiles/bluefox2_test.dir/build.make CMakeFiles/bluefox2_test.dir/bluefox/bluefox2.cpp.s
	$(MAKE) -f CMakeFiles/blueflow.dir/build.make CMakeFiles/blueflow.dir/bluefox/bluefox2.cpp.s
	$(MAKE) -f CMakeFiles/px4flow.dir/build.make CMakeFiles/px4flow.dir/bluefox/bluefox2.cpp.s
	$(MAKE) -f CMakeFiles/videocapture.dir/build.make CMakeFiles/videocapture.dir/bluefox/bluefox2.cpp.s
.PHONY : bluefox/bluefox2.cpp.s

bluefox/bluefox2_setting.o: bluefox/bluefox2_setting.cpp.o

.PHONY : bluefox/bluefox2_setting.o

# target to build an object file
bluefox/bluefox2_setting.cpp.o:
	$(MAKE) -f CMakeFiles/grid.dir/build.make CMakeFiles/grid.dir/bluefox/bluefox2_setting.cpp.o
	$(MAKE) -f CMakeFiles/bluefox2_capture.dir/build.make CMakeFiles/bluefox2_capture.dir/bluefox/bluefox2_setting.cpp.o
	$(MAKE) -f CMakeFiles/videosample.dir/build.make CMakeFiles/videosample.dir/bluefox/bluefox2_setting.cpp.o
	$(MAKE) -f CMakeFiles/bluefox2_test.dir/build.make CMakeFiles/bluefox2_test.dir/bluefox/bluefox2_setting.cpp.o
	$(MAKE) -f CMakeFiles/blueflow.dir/build.make CMakeFiles/blueflow.dir/bluefox/bluefox2_setting.cpp.o
	$(MAKE) -f CMakeFiles/px4flow.dir/build.make CMakeFiles/px4flow.dir/bluefox/bluefox2_setting.cpp.o
	$(MAKE) -f CMakeFiles/videocapture.dir/build.make CMakeFiles/videocapture.dir/bluefox/bluefox2_setting.cpp.o
.PHONY : bluefox/bluefox2_setting.cpp.o

bluefox/bluefox2_setting.i: bluefox/bluefox2_setting.cpp.i

.PHONY : bluefox/bluefox2_setting.i

# target to preprocess a source file
bluefox/bluefox2_setting.cpp.i:
	$(MAKE) -f CMakeFiles/grid.dir/build.make CMakeFiles/grid.dir/bluefox/bluefox2_setting.cpp.i
	$(MAKE) -f CMakeFiles/bluefox2_capture.dir/build.make CMakeFiles/bluefox2_capture.dir/bluefox/bluefox2_setting.cpp.i
	$(MAKE) -f CMakeFiles/videosample.dir/build.make CMakeFiles/videosample.dir/bluefox/bluefox2_setting.cpp.i
	$(MAKE) -f CMakeFiles/bluefox2_test.dir/build.make CMakeFiles/bluefox2_test.dir/bluefox/bluefox2_setting.cpp.i
	$(MAKE) -f CMakeFiles/blueflow.dir/build.make CMakeFiles/blueflow.dir/bluefox/bluefox2_setting.cpp.i
	$(MAKE) -f CMakeFiles/px4flow.dir/build.make CMakeFiles/px4flow.dir/bluefox/bluefox2_setting.cpp.i
	$(MAKE) -f CMakeFiles/videocapture.dir/build.make CMakeFiles/videocapture.dir/bluefox/bluefox2_setting.cpp.i
.PHONY : bluefox/bluefox2_setting.cpp.i

bluefox/bluefox2_setting.s: bluefox/bluefox2_setting.cpp.s

.PHONY : bluefox/bluefox2_setting.s

# target to generate assembly for a file
bluefox/bluefox2_setting.cpp.s:
	$(MAKE) -f CMakeFiles/grid.dir/build.make CMakeFiles/grid.dir/bluefox/bluefox2_setting.cpp.s
	$(MAKE) -f CMakeFiles/bluefox2_capture.dir/build.make CMakeFiles/bluefox2_capture.dir/bluefox/bluefox2_setting.cpp.s
	$(MAKE) -f CMakeFiles/videosample.dir/build.make CMakeFiles/videosample.dir/bluefox/bluefox2_setting.cpp.s
	$(MAKE) -f CMakeFiles/bluefox2_test.dir/build.make CMakeFiles/bluefox2_test.dir/bluefox/bluefox2_setting.cpp.s
	$(MAKE) -f CMakeFiles/blueflow.dir/build.make CMakeFiles/blueflow.dir/bluefox/bluefox2_setting.cpp.s
	$(MAKE) -f CMakeFiles/px4flow.dir/build.make CMakeFiles/px4flow.dir/bluefox/bluefox2_setting.cpp.s
	$(MAKE) -f CMakeFiles/videocapture.dir/build.make CMakeFiles/videocapture.dir/bluefox/bluefox2_setting.cpp.s
.PHONY : bluefox/bluefox2_setting.cpp.s

bluefox/flow.o: bluefox/flow.cpp.o

.PHONY : bluefox/flow.o

# target to build an object file
bluefox/flow.cpp.o:
	$(MAKE) -f CMakeFiles/grid.dir/build.make CMakeFiles/grid.dir/bluefox/flow.cpp.o
	$(MAKE) -f CMakeFiles/bluefox2_capture.dir/build.make CMakeFiles/bluefox2_capture.dir/bluefox/flow.cpp.o
	$(MAKE) -f CMakeFiles/videosample.dir/build.make CMakeFiles/videosample.dir/bluefox/flow.cpp.o
	$(MAKE) -f CMakeFiles/bluefox2_test.dir/build.make CMakeFiles/bluefox2_test.dir/bluefox/flow.cpp.o
	$(MAKE) -f CMakeFiles/blueflow.dir/build.make CMakeFiles/blueflow.dir/bluefox/flow.cpp.o
	$(MAKE) -f CMakeFiles/px4flow.dir/build.make CMakeFiles/px4flow.dir/bluefox/flow.cpp.o
	$(MAKE) -f CMakeFiles/videocapture.dir/build.make CMakeFiles/videocapture.dir/bluefox/flow.cpp.o
.PHONY : bluefox/flow.cpp.o

bluefox/flow.i: bluefox/flow.cpp.i

.PHONY : bluefox/flow.i

# target to preprocess a source file
bluefox/flow.cpp.i:
	$(MAKE) -f CMakeFiles/grid.dir/build.make CMakeFiles/grid.dir/bluefox/flow.cpp.i
	$(MAKE) -f CMakeFiles/bluefox2_capture.dir/build.make CMakeFiles/bluefox2_capture.dir/bluefox/flow.cpp.i
	$(MAKE) -f CMakeFiles/videosample.dir/build.make CMakeFiles/videosample.dir/bluefox/flow.cpp.i
	$(MAKE) -f CMakeFiles/bluefox2_test.dir/build.make CMakeFiles/bluefox2_test.dir/bluefox/flow.cpp.i
	$(MAKE) -f CMakeFiles/blueflow.dir/build.make CMakeFiles/blueflow.dir/bluefox/flow.cpp.i
	$(MAKE) -f CMakeFiles/px4flow.dir/build.make CMakeFiles/px4flow.dir/bluefox/flow.cpp.i
	$(MAKE) -f CMakeFiles/videocapture.dir/build.make CMakeFiles/videocapture.dir/bluefox/flow.cpp.i
.PHONY : bluefox/flow.cpp.i

bluefox/flow.s: bluefox/flow.cpp.s

.PHONY : bluefox/flow.s

# target to generate assembly for a file
bluefox/flow.cpp.s:
	$(MAKE) -f CMakeFiles/grid.dir/build.make CMakeFiles/grid.dir/bluefox/flow.cpp.s
	$(MAKE) -f CMakeFiles/bluefox2_capture.dir/build.make CMakeFiles/bluefox2_capture.dir/bluefox/flow.cpp.s
	$(MAKE) -f CMakeFiles/videosample.dir/build.make CMakeFiles/videosample.dir/bluefox/flow.cpp.s
	$(MAKE) -f CMakeFiles/bluefox2_test.dir/build.make CMakeFiles/bluefox2_test.dir/bluefox/flow.cpp.s
	$(MAKE) -f CMakeFiles/blueflow.dir/build.make CMakeFiles/blueflow.dir/bluefox/flow.cpp.s
	$(MAKE) -f CMakeFiles/px4flow.dir/build.make CMakeFiles/px4flow.dir/bluefox/flow.cpp.s
	$(MAKE) -f CMakeFiles/videocapture.dir/build.make CMakeFiles/videocapture.dir/bluefox/flow.cpp.s
.PHONY : bluefox/flow.cpp.s

bluefox/gridcounter.o: bluefox/gridcounter.cpp.o

.PHONY : bluefox/gridcounter.o

# target to build an object file
bluefox/gridcounter.cpp.o:
	$(MAKE) -f CMakeFiles/grid.dir/build.make CMakeFiles/grid.dir/bluefox/gridcounter.cpp.o
	$(MAKE) -f CMakeFiles/bluefox2_capture.dir/build.make CMakeFiles/bluefox2_capture.dir/bluefox/gridcounter.cpp.o
	$(MAKE) -f CMakeFiles/videosample.dir/build.make CMakeFiles/videosample.dir/bluefox/gridcounter.cpp.o
	$(MAKE) -f CMakeFiles/bluefox2_test.dir/build.make CMakeFiles/bluefox2_test.dir/bluefox/gridcounter.cpp.o
	$(MAKE) -f CMakeFiles/blueflow.dir/build.make CMakeFiles/blueflow.dir/bluefox/gridcounter.cpp.o
	$(MAKE) -f CMakeFiles/px4flow.dir/build.make CMakeFiles/px4flow.dir/bluefox/gridcounter.cpp.o
	$(MAKE) -f CMakeFiles/videocapture.dir/build.make CMakeFiles/videocapture.dir/bluefox/gridcounter.cpp.o
.PHONY : bluefox/gridcounter.cpp.o

bluefox/gridcounter.i: bluefox/gridcounter.cpp.i

.PHONY : bluefox/gridcounter.i

# target to preprocess a source file
bluefox/gridcounter.cpp.i:
	$(MAKE) -f CMakeFiles/grid.dir/build.make CMakeFiles/grid.dir/bluefox/gridcounter.cpp.i
	$(MAKE) -f CMakeFiles/bluefox2_capture.dir/build.make CMakeFiles/bluefox2_capture.dir/bluefox/gridcounter.cpp.i
	$(MAKE) -f CMakeFiles/videosample.dir/build.make CMakeFiles/videosample.dir/bluefox/gridcounter.cpp.i
	$(MAKE) -f CMakeFiles/bluefox2_test.dir/build.make CMakeFiles/bluefox2_test.dir/bluefox/gridcounter.cpp.i
	$(MAKE) -f CMakeFiles/blueflow.dir/build.make CMakeFiles/blueflow.dir/bluefox/gridcounter.cpp.i
	$(MAKE) -f CMakeFiles/px4flow.dir/build.make CMakeFiles/px4flow.dir/bluefox/gridcounter.cpp.i
	$(MAKE) -f CMakeFiles/videocapture.dir/build.make CMakeFiles/videocapture.dir/bluefox/gridcounter.cpp.i
.PHONY : bluefox/gridcounter.cpp.i

bluefox/gridcounter.s: bluefox/gridcounter.cpp.s

.PHONY : bluefox/gridcounter.s

# target to generate assembly for a file
bluefox/gridcounter.cpp.s:
	$(MAKE) -f CMakeFiles/grid.dir/build.make CMakeFiles/grid.dir/bluefox/gridcounter.cpp.s
	$(MAKE) -f CMakeFiles/bluefox2_capture.dir/build.make CMakeFiles/bluefox2_capture.dir/bluefox/gridcounter.cpp.s
	$(MAKE) -f CMakeFiles/videosample.dir/build.make CMakeFiles/videosample.dir/bluefox/gridcounter.cpp.s
	$(MAKE) -f CMakeFiles/bluefox2_test.dir/build.make CMakeFiles/bluefox2_test.dir/bluefox/gridcounter.cpp.s
	$(MAKE) -f CMakeFiles/blueflow.dir/build.make CMakeFiles/blueflow.dir/bluefox/gridcounter.cpp.s
	$(MAKE) -f CMakeFiles/px4flow.dir/build.make CMakeFiles/px4flow.dir/bluefox/gridcounter.cpp.s
	$(MAKE) -f CMakeFiles/videocapture.dir/build.make CMakeFiles/videocapture.dir/bluefox/gridcounter.cpp.s
.PHONY : bluefox/gridcounter.cpp.s

bluefox_capture.o: bluefox_capture.cpp.o

.PHONY : bluefox_capture.o

# target to build an object file
bluefox_capture.cpp.o:
	$(MAKE) -f CMakeFiles/bluefox2_capture.dir/build.make CMakeFiles/bluefox2_capture.dir/bluefox_capture.cpp.o
.PHONY : bluefox_capture.cpp.o

bluefox_capture.i: bluefox_capture.cpp.i

.PHONY : bluefox_capture.i

# target to preprocess a source file
bluefox_capture.cpp.i:
	$(MAKE) -f CMakeFiles/bluefox2_capture.dir/build.make CMakeFiles/bluefox2_capture.dir/bluefox_capture.cpp.i
.PHONY : bluefox_capture.cpp.i

bluefox_capture.s: bluefox_capture.cpp.s

.PHONY : bluefox_capture.s

# target to generate assembly for a file
bluefox_capture.cpp.s:
	$(MAKE) -f CMakeFiles/bluefox2_capture.dir/build.make CMakeFiles/bluefox2_capture.dir/bluefox_capture.cpp.s
.PHONY : bluefox_capture.cpp.s

bluefox_test.o: bluefox_test.cpp.o

.PHONY : bluefox_test.o

# target to build an object file
bluefox_test.cpp.o:
	$(MAKE) -f CMakeFiles/bluefox2_test.dir/build.make CMakeFiles/bluefox2_test.dir/bluefox_test.cpp.o
.PHONY : bluefox_test.cpp.o

bluefox_test.i: bluefox_test.cpp.i

.PHONY : bluefox_test.i

# target to preprocess a source file
bluefox_test.cpp.i:
	$(MAKE) -f CMakeFiles/bluefox2_test.dir/build.make CMakeFiles/bluefox2_test.dir/bluefox_test.cpp.i
.PHONY : bluefox_test.cpp.i

bluefox_test.s: bluefox_test.cpp.s

.PHONY : bluefox_test.s

# target to generate assembly for a file
bluefox_test.cpp.s:
	$(MAKE) -f CMakeFiles/bluefox2_test.dir/build.make CMakeFiles/bluefox2_test.dir/bluefox_test.cpp.s
.PHONY : bluefox_test.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/grid.dir/build.make CMakeFiles/grid.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/grid.dir/build.make CMakeFiles/grid.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/grid.dir/build.make CMakeFiles/grid.dir/main.cpp.s
.PHONY : main.cpp.s

px4flow.o: px4flow.cpp.o

.PHONY : px4flow.o

# target to build an object file
px4flow.cpp.o:
	$(MAKE) -f CMakeFiles/px4flow.dir/build.make CMakeFiles/px4flow.dir/px4flow.cpp.o
.PHONY : px4flow.cpp.o

px4flow.i: px4flow.cpp.i

.PHONY : px4flow.i

# target to preprocess a source file
px4flow.cpp.i:
	$(MAKE) -f CMakeFiles/px4flow.dir/build.make CMakeFiles/px4flow.dir/px4flow.cpp.i
.PHONY : px4flow.cpp.i

px4flow.s: px4flow.cpp.s

.PHONY : px4flow.s

# target to generate assembly for a file
px4flow.cpp.s:
	$(MAKE) -f CMakeFiles/px4flow.dir/build.make CMakeFiles/px4flow.dir/px4flow.cpp.s
.PHONY : px4flow.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... grid"
	@echo "... bluefox2_capture"
	@echo "... edit_cache"
	@echo "... videosample"
	@echo "... bluefox2_test"
	@echo "... blueflow"
	@echo "... px4flow"
	@echo "... videocapture"
	@echo "... VideoCapture.o"
	@echo "... VideoCapture.i"
	@echo "... VideoCapture.s"
	@echo "... VideoSample.o"
	@echo "... VideoSample.i"
	@echo "... VideoSample.s"
	@echo "... blueflow.o"
	@echo "... blueflow.i"
	@echo "... blueflow.s"
	@echo "... bluefox/bluefox2.o"
	@echo "... bluefox/bluefox2.i"
	@echo "... bluefox/bluefox2.s"
	@echo "... bluefox/bluefox2_setting.o"
	@echo "... bluefox/bluefox2_setting.i"
	@echo "... bluefox/bluefox2_setting.s"
	@echo "... bluefox/flow.o"
	@echo "... bluefox/flow.i"
	@echo "... bluefox/flow.s"
	@echo "... bluefox/gridcounter.o"
	@echo "... bluefox/gridcounter.i"
	@echo "... bluefox/gridcounter.s"
	@echo "... bluefox_capture.o"
	@echo "... bluefox_capture.i"
	@echo "... bluefox_capture.s"
	@echo "... bluefox_test.o"
	@echo "... bluefox_test.i"
	@echo "... bluefox_test.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... px4flow.o"
	@echo "... px4flow.i"
	@echo "... px4flow.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

